version: "3.9"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # API
      - "9090:9090"   # Web console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    command: server /data --console-address ":9090"
    volumes:
      - ./data:/data      # persist uploaded objects
      - ./config:/root/.minio  # persist config (users, policies, etc.)
